### ISSUE TITLE
tasks/security/authorization/authz-td-migration fails with 1.8.0-alpha.2 update

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#8405]
The tests in the second section of the page are failing. It receives a `503` instead of a `403` for both tests.

Failing:
```
VERIFY FAILED snip_migrate_trust_domain_without_trust_domain_aliases_4 (timeout after 120s): received: "503", expected: "403"
```

Pointer to Slack discussion: https://istio.slack.com/archives/C3TEGNZ7W/p1604061921132200

For now, the two failing tests have been commented out in https://github.com/istio/istio.io/pull/8399 so the alpha.2 release can be used for other tests. They will need to be re-enabled once this is fixed.

**Comment by ericvn** [comment]
So trying the page manually, and in the second part: https://preliminary.istio.io/latest/docs/tasks/security/authorization/authz-td-migration/#migrate-trust-domain-without-trust-domain-aliases Step 3 says I should get 403's from both curls.  I am getting 503's from both.

In the next section, I also have a failure:

cat <<EOF > ./td-installation.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      trustDomain: new-td
      trustDomainAliases:
        - old-td
EOF
istioctl install --set profile=demo -f td-installation.yaml -y
Error: failed to install manifests: validation errors (use --force to override):
unknown field "trustDomainAliases" in v1alpha1.GlobalConfig

**Comment by ericvn** [comment]
Updated yaml to be:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    trustDomain: new-td
    trustDomainAliases:
      - old-td
```
and that installed.

**Comment by ericvn** [comment]
Based on the tests, I conclude the prior yaml wasn't working in 1.7 either, so maybe not a compatibility issue.

**Comment by bianpengyuan** [comment]
@yangminzhu Assign this to you for triage. This is marked as 1.8 release blocker. Please take a look asap. thanks!

**Comment by bianpengyuan** [comment]
Fixed by https://github.com/istio/istio.io/issues/8405? @howardjohn

**Comment by howardjohn** [comment]
Should be fixed now

**Comment by ericvn** [comment]
Running the test case locally after adding back in the two verify's still fails. I will try and pull the alpha.3 build and try again manually against the docs.

**Comment by howardjohn** [comment]
I am pretty sure its from https://github.com/istio/istio/issues/28756. Basically, istiod used to be implicitly restarted by `istioctl install`. Now it isn't. So we can either fix that issue or add `kubectl rollout restart deployment istiod -n istio-system` to the doc before restarting the sleep pods

**Comment by ericvn** [comment]
Adding the istiod restart in the docs/test does get the test to pass.

The question is if it is considered a regression to no longer do an automated restart of istiod during the `Istioctl install`?

I understand that this particular task is not referenced often, and is not the preferred way to migrate trust domains, so maybe it's not a major issue.

It should require something in the upgrade notes that an istiod restart may be required after an `istioctl install`.

**Comment by bianpengyuan** [comment]
Any update on this? Shall we just add a step to the doc and fix it in patch releases? @yangminzhu

**Comment by ericvn** [comment]
Currently, I've added the step in the docs/test to redeploy istiod after the istioctl install and things are working.

As noted in my prior remarks, I'm not sure if this an acceptable solution along with a note in the upgrade docs that istioctl install no longer causes a restart of istiod (is this statement global, or maybe it's only true if there is a change in the trust domain). If the powers that be, think that is acceptable, then we still need to upgrade note, but the docs/test work is complete.

**Comment by yangminzhu** [comment]
I think it's fine to ask users to redeploy istiod for this specific task, thanks for the update @ericvn ! I'm not sure if the behavior change in istioctl install needs a global upgrade note (probably should?) but I think that is a separate topic.

**Comment by ericvn** [comment]
I'll close this issue since it is fixed. Will add a comment in the upgrade note PR/issue with a pointer to this problem.

**Comment by ericvn** [comment]
As an FYI, https://github.com/istio/istio/issues/28756 implies that the restart is just not happening in the case of trust domain changes, so only affects a small number of users and the docs now mention a restart is needed.
